name: Release Platform Tools Linux

on:
  push:
    tags:
      - 'platform-tools-linux-v*'

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      working-directory: assets/platform-tools-linux
    permissions:
      contents: write
      id-token: write
