name: Release Platform Tools Darwin

on:
  push:
    tags:
      - 'platform-tools-darwin-v*'

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      working-directory: assets/platform-tools-darwin
    permissions:
      contents: write
      id-token: write
