name: Release Platform Tools Windows

on:
  push:
    tags:
      - 'platform-tools-windows-v*'

jobs:
  release:
    uses: ./.github/workflows/release.yml
    with:
      working-directory: assets/platform-tools-windows
    permissions:
      contents: write
      id-token: write
